<?php

if ( ! function_exists( 'gracey_core_add_kiko_icons_to_collection' ) ) {
    /**
     * Function that add icon font pack into the global list
     *
     * @param array $icons
     *
     * @return array
     */
    function gracey_core_add_kiko_icons_to_collection( $icons ) {
        $icons[] = 'GraceyCore_Kiko_Icons_Pack';

        return $icons;
    }

    add_filter( 'qode_framework_filter_add_icon', 'gracey_core_add_kiko_icons_to_collection' );
}

if ( class_exists( 'QodeFrameworkIconPack' ) ) {
    class GraceyCore_Kiko_Icons_Pack extends QodeFrameworkIconPack {

        public function __construct() {
            parent::__construct();
        }

        public function add_icon_pack() {
            $this->set_base( 'kiko' );
            $this->set_name( 'Kiko Icons' );
            $this->set_icons( $this->icons_array() );
            $this->set_specific_icons( $this->specific_icons() );
        }

        public function get_style_url() {
            return GRACEY_CORE_INC_URL_PATH . '/icons/' . $this->get_base() . '/assets/css/kiko-all.min.css';
        }

        private function icons_array() {
            $icons_initial_array =  array(
                'kiko-train kikos' => '\f001',
                'kiko-car kikos' => '\f002',
                'kiko-truck kikos' => '\f003',
                'kiko-bike kikos' => '\f004',
                'kiko-sailboat kikos' => '\f005',
                'kiko-airplane kikos' => '\f006',
                'kiko-helicopter kikos' => '\f007',
                'kiko-motor-scooter kikos' => '\f008',
                'kiko-motorcycle kikos' => '\f009',
                'kiko-air-balloon kikos' => '\f010',
                'kiko-plane-takes-off kikos' => '\f011',
                'kiko-plane-lands kikos' => '\f012',
                'kiko-bus kikos' => '\f013',
                'kiko-cargo-vessel kikos' => '\f014',
                'kiko-electromobile kikos' => '\f015',
                'kiko-rocket kikos' => '\f016',
                'kiko-rocket-shuttle kikos' => '\f017',
                'kiko-ambulance kikos' => '\f018',
                'kiko-police kikos' => '\f019',
                'kiko-tank kikos' => '\f020',
                'kiko-tractor kikos' => '\f021',
                'kiko-tow-truck kikos' => '\f022',
                'kiko-airship kikos' => '\f023',
                'kiko-scooter kikos' => '\f024',
                'kiko-self-balancing-scooter kikos' => '\f025',
                'kiko-segway kikos' => '\f026',
                'kiko-metro kikos' => '\f027',
                'kiko-syringe kikos' => '\f028',
                'kiko-pills kikos' => '\f029',
                'kiko-microscope kikos' => '\f030',
                'kiko-jar-of-medicine kikos' => '\f031',
                'kiko-tubes kikos' => '\f032',
                'kiko-medicine kikos' => '\f033',
                'kiko-toilet kikos' => '\f034',
                'kiko-patch kikos' => '\f035',
                'kiko-pregnancy kikos' => '\f036',
                'kiko-medical-app kikos' => '\f037',
                'kiko-herbs kikos' => '\f038',
                'kiko-recipe kikos' => '\f039',
                'kiko-crushing-of-medicines kikos' => '\f040',
                'kiko-blood kikos' => '\f041',
                'kiko-donor kikos' => '\f042',
                'kiko-brain kikos' => '\f043',
                'kiko-kidneys kikos' => '\f044',
                'kiko-liver kikos' => '\f045',
                'kiko-lungs kikos' => '\f046',
                'kiko-heart kikos' => '\f047',
                'kiko-intestine kikos' => '\f048',
                'kiko-stomach kikos' => '\f049',
                'kiko-healthy-tooth kikos' => '\f050',
                'kiko-aching-tooth kikos' => '\f051',
                'kiko-nose kikos' => '\f052',
                'kiko-ear kikos' => '\f053',
                'kiko-eye kikos' => '\f054',
                'kiko-chest kikos' => '\f055',
                'kiko-doctor kikos' => '\f056',
                'kiko-doctor-woman kikos' => '\f057',
                'kiko-scheduled-med kikos' => '\f058',
                'kiko-hand kikos' => '\f059',
                'kiko-foot kikos' => '\f060',
                'kiko-hospital kikos' => '\f061',
                'kiko-stethoscope kikos' => '\f062',
                'kiko-bacteria kikos' => '\f063',
                'kiko-DNA kikos' => '\f064',
                'kiko-spine kikos' => '\f065,',
                'kiko-bed-rest kikos' => '\f066',
                'kiko-bone kikos' => '\f067',
                'kiko-medical-cross kikos' => '\f068',
                'kiko-medical-cross-usa kikos' => '\f069',
                'kiko-dropper kikos' => '\f070',
                'kiko-heart-rate kikos' => '\f071',
                'kiko-marijuana kikos' => '\f072',
                'kiko-fracture kikos' => '\f073',
                'kiko-urine kikos' => '\f074',
                'kiko-fecal kikos' => '\f075',
                'kiko-diagnostics kikos' => '\f076',
                'kiko-allergy kikos' => '\f077',
                'kiko-call-med kikos' => '\f078',
                'kiko-crutches kikos' => '\f079',
                'kiko-wheelchair kikos' => '\f080',
                'kiko-skull kikos' => '\f081',
                'kiko-childbirth kikos' => '\f082',
                'kiko-vitamins kikos' => '\f083',
                'kiko-exclamation-circle kikos' => '\f084',
                'kiko-exclamation-triangle kikos' => '\f085',
                'kiko-arrow-down-circle kikos' => '\f086',
                'kiko-arrow-up-circle kikos' => '\f087',
                'kiko-arrow-left-circle kikos' => '\f088',
                'kiko-arrow-right-circle kikos' => '\f089',
                'kiko-arrow-up kikos' => '\f090',
                'kiko-arrow-down kikos' => '\f091',
                'kiko-arrow-right kikos' => '\f092',
                'kiko-arrow-left kikos' => '\f093',
                'kiko-double-arrow-up kikos' => '\f094',
                'kiko-double-arrow-down kikos' => '\f095',
                'kiko-double-arrow-left kikos' => '\f096',
                'kiko-double-arrow-right kikos' => '\f097',
                'kiko-clip kikos' => '\f098',
                'kiko-triangular-arrow-up kikos' => '\f099',
                'kiko-triangular-arrow-down kikos' => '\f100',
                'kiko-triangular-arrow-left kikos' => '\f101',
                'kiko-triangular-arrow-right kikos' => '\f102',
                'kiko-email-at kikos' => '\f103',
                'kiko-signal kikos' => '\f104',
                'kiko-bad-signal kikos' => '\f105',
                'kiko-no-signal kikos' => '\f106',
                'kiko-video kikos' => '\f107',
                'kiko-sound-on kikos' => '\f108',
                'kiko-sound-off kikos' => '\f109',
                'kiko-call-on kikos' => '\f110',
                'kiko-call-off kikos' => '\f111',
                'kiko-bluetooth kikos' => '\f112',
                'kiko-wifi kikos' => '\f113',
                'kiko-book-open kikos' => '\f114',
                'kiko-book-close kikos' => '\f115',
                'kiko-bookmark kikos' => '\f116',
                'kiko-light-turn-on kikos' => '\f117',
                'kiko-light-turn-off kikos' => '\f118',
                'kiko-brush kikos' => '\f119',
                'kiko-full-battery kikos' => '\f120',
                'kiko-half-empty-battery kikos' => '\f121',
                'kiko-empty-battery kikos' => '\f122',
                'kiko-check-circle kikos' => '\f123',
                'kiko-check-square kikos' => '\f124',
                'kiko-check kikos' => '\f125',
                'kiko-cross-circle kikos' => '\f126',
                'kiko-cross-square kikos' => '\f127',
                'kiko-cross kikos' => '\f128',
                'kiko-clock kikos' => '\f129',
                'kiko-cloud-download kikos' => '\f130',
                'kiko-cloud-load kikos' => '\f131',
                'kiko-cloud kikos' => '\f132',
                'kiko-loading kikos' => '\f133',
                'kiko-credit-card kikos' => '\f134',
                'kiko-crop kikos' => '\f135',
                'kiko-pencil kikos' => '\f136',
                'kiko-pencil-write kikos' => '\f137',
                'kiko-drop kikos' => '\f138',
                'kiko-no-drop kikos' => '\f139',
                'kiko-email kikos' => '\f140',
                'kiko-email-open kikos' => '\f141',
                'kiko-email-forward kikos' => '\f142',
                'kiko-email-deleted kikos' => '\f143',
                'kiko-email-attachment kikos' => '\f144',
                'kiko-emails kikos' => '\f145',
                'kiko-expand kikos' => '\f146',
                'kiko-open-eye kikos' => '\f147',
                'kiko-no-eye kikos' => '\f148',
                'kiko-trash kikos' => '\f149',
                'kiko-sheet kikos' => '\f150',
                'kiko-sheet-plus kikos' => '\f151',
                'kiko-sheet-minus kikos' => '\f152',
                'kiko-sheet-text kikos' => '\f153',
                'kiko-video-file kikos' => '\f154',
                'kiko-flag kikos' => '\f155',
                'kiko-gift kikos' => '\f156',
                'kiko-globe-europe kikos' => '\f157',
                'kiko-globe-north-america kikos' => '\f158',
                'kiko-globe-asia kikos' => '\f159',
                'kiko-globe-australia kikos' => '\f160',
                'kiko-globe kikos' => '\f161',
                'kiko-home kikos' => '\f162',
                'kiko-hashtag kikos' => '\f163',
                'kiko-headphones kikos' => '\f164',
                'kiko-microphone kikos' => '\f165',
                'kiko-microphone-off kikos' => '\f166',
                'kiko-link kikos' => '\f167',
                'kiko-zoom kikos' => '\f168',
                'kiko-zoom-minus kikos' => '\f169',
                'kiko-zoom-plus kikos' => '\f170',
                'kiko-heart-symbol kikos' => '\f171',
                'kiko-picture kikos' => '\f172',
                'kiko-information kikos' => '\f173',
                'kiko-layers kikos' => '\f174',
                'kiko-hamburger-menu kikos' => '\f175',
                'kiko-plus kikos' => '\f176',
                'kiko-circle-plus kikos' => '\f177',
                'kiko-square-plus kikos' => '\f178',
                'kiko-pause kikos' => '\f179',
                'kiko-record kikos' => '\f180',
                'kiko-forward kikos' => '\f181',
                'kiko-previous kikos' => '\f182',
                'kiko-note kikos' => '\f183',
                'kiko-treble-clef kikos' => '\f184',
                'kiko-navigation kikos' => '\f185',
                'kiko-moon kikos' => '\f186',
                'kiko-sun kikos' => '\f187',
                'kiko-comment kikos' => '\f188',
                'kiko-dialogue kikos' => '\f189',
                'kiko-user kikos' => '\f190',
                'kiko-user-add kikos' => '\f191',
                'kiko-user-minus kikos' => '\f192',
                'kiko-user-check kikos' => '\f193',
                'kiko-user-x kikos' => '\f194',
                'kiko-users kikos' => '\f195',
                'kiko-phone kikos' => '\f196',
                'kiko-turn-off-phone kikos' => '\f197',
                'kiko-question kikos' => '\f198',
                'kiko-label kikos' => '\f199',
                'kiko-off kikos' => '\f200',
                'kiko-shield kikos' => '\f201',
                'kiko-shield-crossed kikos' => '\f202',
                'kiko-gear kikos' => '\f203',
                'kiko-several-gears kikos' => '\f204',
                'kiko-wrench kikos' => '\f205',
                'kiko-shopping-cart kikos' => '\f206',
                'kiko-shopping-cart-add kikos' => '\f207',
                'kiko-shopping-cart-delete kikos' => '\f208',
                'kiko-shopping-cart-pay kikos' => '\f209',
                'kiko-shopping-basket kikos' => '\f210',
                'kiko-shopping-basket-add kikos' => '\f211',
                'kiko-shopping-basket-delete kikos' => '\f212',
                'kiko-termometer-minus kikos' => '\f213',
                'kiko-termometer-plus kikos' => '\f214',
                'kiko-star kikos' => '\f215',
                'kiko-half-star kikos' => '\f216',
                'kiko-text kikos' => '\f217',
                'kiko-lock kikos' => '\f218',
                'kiko-unlock kikos' => '\f219',
                'kiko-umbrella kikos' => '\f220',
                'kiko-save kikos' => '\f221',
                'kiko-save-error kikos' => '\f222',
                'kiko-paper-bag kikos' => '\f223',
                'kiko-circle-checkbox kikos' => '\f224',
                'kiko-circle-checkbox-full kikos' => '\f225',
                'kiko-square-checkbox kikos' => '\f226',
                'kiko-square-checkbox-full kikos' => '\f227',
                'kiko-marker-map kikos' => '\f228',
                'kiko-pin kikos' => '\f229',
                'kiko-map kikos' => '\f230',
                'kiko-lightning kikos' => '\f231',
                'kiko-lightning-off kikos' => '\f232',
                'kiko-pipette kikos' => '\f233',
                'kiko-compass kikos' => '\f234',
                'kiko-copy kikos' => '\f235',
                'kiko-cut kikos' => '\f236',
                'kiko-past kikos' => '\f237',
                'kiko-information-symbol kikos' => '\f238',
                'kiko-download-file kikos' => '\f239',
                'kiko-broken-link kikos' => '\f240',
                'kiko-email-read kikos' => '\f241',
                'kiko-spam kikos' => '\f242',
                'kiko-globe-latin-america kikos' => '\f243',
                'kiko-globe-japan kikos' => '\f244',
                'kiko-globe-africa kikos' => '\f245',
                'kiko-globe-east kikos' => '\f246',
                'kiko-globe-antarctic kikos' => '\f247',
                'kiko-fire kikos' => '\f248',
                'kiko-support kikos' => '\f249',
                'kiko-recycle-symbol kikos' => '\f250',
                'kiko-reload-arrow kikos' => '\f251',
                'kiko-cross-line kikos' => '\f252',
                'kiko-check-line kikos' => '\f253',
                'kiko-plus-line kikos' => '\f254',
                'kiko-timer kikos' => '\f255',
                'kiko-alarm kikos' => '\f256',
                'kiko-alarm-off kikos' => '\f257',
                'kiko-fingerprint kikos' => '\f258',
                'kiko-scan-fingerprint kikos' => '\f259',
                'kiko-computer-virus kikos' => '\f260',
                'kiko-the-compass kikos' => '\f234',
                'kiko-wifi-off kikos' => '\f261',
                'kiko-quote-left kikos' => '\f262',
                'kiko-quote-right kikos' => '\f263',
                'kiko-ellipsis-menu-v kikos' => '\f264',
                'kiko-ellipsis-menu-h kikos' => '\f265',
                'kiko-iphone kikos' => '\f266',
                'kiko-android-phone kikos' => '\f267',
                'kiko-google-pixel-phone kikos' => '\f268',
                'kiko-old-phone kikos' => '\f269',
                'kiko-nokia-3310 kikos' => '\f270',
                'kiko-bendable-smartphone kikos' => '\f271',
                'kiko-tablet kikos' => '\f272',
                'kiko-imac-computer kikos' => '\f274',
                'kiko-notebook kikos' => '\f275',
                'kiko-top-notebook kikos' => '\f276',
                'kiko-screen kikos' => '\f277',
                'kiko-mouse kikos' => '\f278',
                'kiko-graphic-pen kikos' => '\f279',
                'kiko-vr kikos' => '\f280',
                'kiko-google-glass kikos' => '\f281',
                'kiko-graphics-tablet kikos' => '\f282',
                'kiko-printer kikos' => '\f283',
                'kiko-scanner kikos' => '\f284',
                'kiko-warehouse-scanner kikos' => '\f285',
                'kiko-iwatch kikos' => '\f286',
                'kiko-smart-watch kikos' => '\f287',
                'kiko-navigator kikos' => '\f288',
                'kiko-dashcam kikos' => '\f289',
                'kiko-music-speaker kikos' => '\f290',
                'kiko-yandex-alice kikos' => '\f291',
                'kiko-cortana-station kikos' => '\f292',
                'kiko-hello-google kikos' => '\f293',
                'kiko-amazon-station kikos' => '\f294',
                'kiko-web-camera kikos' => '\f295',
                'kiko-desktop-microphone kikos' => '\f296',
                'kiko-earphones kikos' => '\f297',
                'kiko-music-headphones kikos' => '\f298',
                'kiko-headphones-microphone kikos' => '\f299',
                'kiko-cable kikos' => '\f300',
                'kiko-socket-eu kikos' => '\f301',
                'kiko-socket-us kikos' => '\f302',
                'kiko-fitness-bracelet kikos' => '\f303',
                'kiko-gps-tracker kikos' => '\f304',
                'kiko-satellite-communication kikos' => '\f305',
                'kiko-television kikos' => '\f306',
                'kiko-digital-tv kikos' => '\f307',
                'kiko-router kikos' => '\f308',
                'kiko-external-drive kikos' => '\f309',
                'kiko-go-pro-camera kikos' => '\f310',
                'kiko-quadcopter kikos' => '\f311',
                'kiko-radio kikos' => '\f312',
                'kiko-transmitter kikos' => '\f313',
                'kiko-baby-radio-monitor kikos' => '\f314',
                'kiko-baby-monitor kikos' => '\f315',
                'kiko-joystick kikos' => '\f316',
                'kiko-portable-console kikos' => '\f317',
                'kiko-ipod kikos' => '\f318',
                'kiko-handsfree kikos' => '\f319',
                'kiko-camera kikos' => '\f320',
                'kiko-professional-camera kikos' => '\f321',
                'kiko-professional-video-camera kikos' => '\f322',
                'kiko-journalist-microphone kikos' => '\f323',
                'kiko-studio-lighting kikos' => '\f324',
                'kiko-robot-pet kikos' => '\f325',
                'kiko-robot-vacuum-cleaner kikos' => '\f326',
                'kiko-robot-big-dog kikos' => '\f327',
                'kiko-humanoid-robot kikos' => '\f328',
                'kiko-robot kikos' => '\f329',
                'kiko-robot-head kikos' => '\f330',
                'kiko-desktop-computer kikos' => '\f273',
                'kiko-anchor kikos' => '\f331',
                'kiko-calendar kikos' => '\f332',
                'kiko-schedule kikos' => '\f333',
                'kiko-address-book kikos' => '\f334',
                'kiko-facebook kikos' => '\f335',
                'kiko-twitter kikos' => '\f336',
                'kiko-dribbble kikos' => '\f337',
                'kiko-behance kikos' => '\f338',
                'kiko-pinterest kikos' => '\f339',
                'kiko-vkontakte kikos' => '\f340',
                'kiko-odnoklassniki kikos' => '\f341',
                'kiko-flipboard kikos' => '\f342',
                'kiko-whatsapp kikos' => '\f343',
                'kiko-blogger kikos' => '\f344',
                'kiko-evernote kikos' => '\f345',
                'kiko-gmail kikos' => '\f346',
                'kiko-line kikos' => '\f347',
                'kiko-myspace kikos' => '\f348',
                'kiko-pocket kikos' => '\f349',
                'kiko-skype kikos' => '\f350',
                'kiko-viadeo kikos' => '\f351',
                'kiko-xing kikos' => '\f352',
                'kiko-linkedin kikos' => '\f353',
                'kiko-naver kikos' => '\f354',
                'kiko-stumbleupon kikos' => '\f355',
                'kiko-viber kikos' => '\f356',
                'kiko-snapchat kikos' => '\f357',
                'kiko-yammer kikos' => '\f358',
                'kiko-digg kikos' => '\f359',
                'kiko-messenger kikos' => '\f360',
                'kiko-live-journal kikos' => '\f361',
                'kiko-newsvine kikos' => '\f362',
                'kiko-qzone kikos' => '\f363',
                'kiko-telegram kikos' => '\f364',
                'kiko-yummly kikos' => '\f365',
                'kiko-douban kikos' => '\f366',
                'kiko-flattr kikos' => '\f367',
                'kiko-hatena kikos' => '\f368',
                'kiko-reddit kikos' => '\f369',
                'kiko-tumblr kikos' => '\f370',
                'kiko-weibo kikos' => '\f371',
                'kiko-google kikos' => '\f372',
                'kiko-yandex kikos' => '\f373',
                'kiko-share kikos' => '\f374',
                'kiko-yandex-aura kikos' => '\f375',
                'kiko-wechat kikos' => '\f376',
                'kiko-baidu kikos' => '\f377',
                'kiko-bing kikos' => '\f378',
                'kiko-like kikos' => '\f379',
                'kiko-unlike kikos' => '\f380',
            );

            $icons = array();
            $icons[""] = "";
            foreach ($icons_initial_array as $key => $value) {
                $new_key = explode(' ', $key);
                $new_key = $new_key[0];
                $new_key = str_replace('kiko-', '', $new_key);
                $new_key = str_replace('-', ' ', $new_key);
                $new_key = ucwords($new_key);

                $icons[$key] = $new_key;
            }

            return $icons;
        }

        function specific_icons() {
            return array(
                'search'        => 'kiko-zoom kikol',
                'dropdown-cart' => 'kiko-shopping-cart kikol',
                'menu'          => 'kiko-ellipsis-menu-v kikos',
                'close'         => 'kiko-cross-line kikol',
                'back-to-top'   => 'kiko-arrow-up kikol',
                'mobile-menu'   => 'kiko-hamburger-menu kikol',
                'quote'         => 'kiko-quote-right kikol',
                'facebook'      => 'kiko-facebook kikos',
                'twitter'       => 'kiko-twitter kikos',
                'linkedin'      => 'kiko-linkedin kikos',
                'pinterest'     => 'kiko-pinterest kikos',
                'tumblr'        => 'kiko-tumblr kikos',
                'vk'            => 'kiko-vkontakte kikos'
            );
        }
    }
}